<%@ taglib prefix="c" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="${pageContext.request.contextPath}/">Stego ACS Web Console</a>

            <div class="nav-collapse collapse">
                <ul class="nav">  <!-- TODO autogenerated li class="active" -->
                    <sec:authorize access="isAuthenticated()">
                        <sec:authorize ifAllGranted="ROLE_ADMIN">
                            <li><a href="${pageContext.request.contextPath}/employees">Employees List</a></li>
                            <li><a href="${pageContext.request.contextPath}/offices" role="button">Offices List</a></li>
                            <li><a href="${pageContext.request.contextPath}/search" role="button">Search an Employee</a></li>
                            <li><a href="${pageContext.request.contextPath}/auth-log" role="button">Authentication Log</a></li>
                            <li><a href="${pageContext.request.contextPath}/j_spring_security_logout" role="button">Logout</a></li>
                        </sec:authorize>
                    </sec:authorize>
                <li><a href="${pageContext.request.contextPath}/passes/check" role="button">Pass Demo</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
